import { ChartLine, ChatCircle, Code, Cpu, Database, FilmSlate, FolderOpen, Globe, House, LockKey, MagnifyingGlass, Package, Robot, Stack, Wrench, type Icon } from "@phosphor-icons/react";

const CATEGORY_ICONS: Record<string, Icon> = { database: Database, cache: Database, web: Globe, runtime: Code, monitoring: ChartLine, cms: FolderOpen, ai: Robot, collaboration: ChatCircle, security: LockKey, storage: Stack, media: FilmSlate, iot: House, analytics: ChartLine, developer: Code, tools: Wrench, messaging: ChatCircle, compute: Cpu, search: MagnifyingGlass };

const TECHNOLOGY_CATEGORIES: Record<string, string> = {
  postgres: "database", postgresql: "database", mysql: "database", mariadb: "database", mongodb: "database", redis: "cache", valkey: "cache", clickhouse: "database", cassandra: "database", neo4j: "database", surrealdb: "database", arangodb: "database", couchdb: "database", influxdb: "database", timescaledb: "database", etcd: "database", opensearch: "search", elasticsearch: "search", meilisearch: "search", qdrant: "database", milvus: "database", dgraph: "database", minio: "storage", rabbitmq: "messaging", kafka: "messaging", nats: "messaging", pulsar: "messaging", nginx: "web", caddy: "web", traefik: "web", apache: "web", envoy: "web", node: "runtime", nodejs: "runtime", python: "runtime", golang: "runtime", go: "runtime", php: "runtime", ruby: "runtime", deno: "runtime", bun: "runtime", dotnet: "runtime", docker: "tools", dockerfile: "tools", image: "tools", oci: "tools", grafana: "monitoring", prometheus: "monitoring", loki: "monitoring", tempo: "monitoring", jaeger: "monitoring", jenkins: "tools", gitlab: "tools", gitea: "tools", forgejo: "tools", vault: "security", vaultwarden: "security", keycloak: "security", authentik: "security", authelia: "security", openvpn: "security", wireguard: "security", wordpress: "cms", ghost: "cms", strapi: "cms", directus: "cms", drupal: "cms", joomla: "cms", bookstack: "cms", appwrite: "developer", supabase: "developer", ollama: "ai", n8n: "tools", dify: "ai", langflow: "ai", mattermost: "collaboration", rocketchat: "collaboration", zulip: "collaboration", nextcloud: "storage", seafile: "storage", jellyfin: "media", plex: "media", emby: "media", sonarr: "media", radarr: "media", transmission: "media", immich: "media", homeassistant: "iot", "node-red": "iot", zigbee2mqtt: "iot", metabase: "analytics", redash: "analytics", superset: "analytics", umami: "analytics", matomo: "analytics", airflow: "tools", jupyter: "developer", mlflow: "ai",
};

export function TechIcon({ name, size = 20, className = "" }: { name?: string; size?: number; className?: string }) {
  const key = (name ?? "").toLowerCase();
  const IconComponent = CATEGORY_ICONS[TECHNOLOGY_CATEGORIES[key] ?? key] ?? Package;
  return <IconComponent size={size} className={className} aria-hidden="true" />;
}
