package application

import (
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var versionNumberPattern = regexp.MustCompile(`^(\d+)`)

func validateRestoreCompatibility(engine, sourceVersion, targetVersion string) error {
	sourceMajor, sourceKnown := majorVersion(sourceVersion)
	targetMajor, targetKnown := majorVersion(targetVersion)
	if !sourceKnown || !targetKnown || strings.EqualFold(targetVersion, "latest") || sourceMajor <= targetMajor {
		return nil
	}
	return fmt.Errorf("backup generated by %s %s, target is %s %s", displayEngine(engine), sourceVersion, displayEngine(engine), targetVersion)
}

func majorVersion(version string) (int, bool) {
	match := versionNumberPattern.FindStringSubmatch(strings.TrimSpace(version))
	if len(match) != 2 {
		return 0, false
	}
	major, err := strconv.Atoi(match[1])
	return major, err == nil
}

func displayEngine(engine string) string {
	if engine == "postgres" {
		return "PostgreSQL"
	}
	return engine
}

func detectUploadVersion(path, format, engine string) (string, error) {
	if engine != "postgres" || (format != "dump" && format != "sql.gz") {
		return "", nil
	}
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	var reader io.Reader = file
	if format == "sql.gz" {
		gz, gzipErr := gzip.NewReader(file)
		if gzipErr != nil {
			return "", fmt.Errorf("invalid gzip archive: %w", gzipErr)
		}
		defer gz.Close()
		reader = gz
	}
	header := make([]byte, 7)
	if _, err := io.ReadFull(reader, header); err != nil {
		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
			return "", errors.New("archive header is incomplete")
		}
		return "", err
	}
	if string(header[:5]) != "PGDMP" {
		if format == "sql.gz" {
			return "", nil
		}
		return "", errors.New("file is not a PostgreSQL archive")
	}
	archiveVersion := int(header[6])
	serverVersion, ok := map[int]string{11: "12", 12: "13", 13: "14", 14: "15", 15: "16", 16: "17", 17: "18"}[archiveVersion]
	if !ok {
		return "", nil
	}
	return serverVersion, nil
}
