package application

import (
	"os"
	"path/filepath"
	"testing"
)

func TestValidateRestoreCompatibility(t *testing.T) {
	if err := validateRestoreCompatibility("postgres", "17", "16"); err == nil {
		t.Fatal("expected newer source version to be rejected")
	} else if err.Error() != "backup generated by PostgreSQL 17, target is PostgreSQL 16" {
		t.Fatalf("unexpected error: %v", err)
	}
	if err := validateRestoreCompatibility("postgres", "16", "17"); err != nil {
		t.Fatalf("expected newer target version to be accepted: %v", err)
	}
	if err := validateRestoreCompatibility("mysql", "8.4", "8.0"); err != nil {
		t.Fatalf("expected same major version to be accepted: %v", err)
	}
}

func TestDetectPostgresArchiveVersion(t *testing.T) {
	path := filepath.Join(t.TempDir(), "backup.dump")
	if err := os.WriteFile(path, []byte{'P', 'G', 'D', 'M', 'P', 1, 16}, 0o600); err != nil {
		t.Fatalf("write archive: %v", err)
	}
	version, err := detectUploadVersion(path, "dump", "postgres")
	if err != nil {
		t.Fatalf("detect version: %v", err)
	}
	if version != "17" {
		t.Fatalf("detected version %q, want 17", version)
	}
	if _, err := detectUploadVersion(path, "dump", "mysql"); err != nil {
		t.Fatalf("unexpected non-Postgres detection error: %v", err)
	}
}
