port: 4222
http: 8222
jetstream {
  store_dir: "/data"
}
authorization {
  users = [
    {
      user: "$AETHER_NATS_USER"
      password: "$AETHER_NATS_PASSWORD_HASH"
      permissions: {
        publish: [
          "aether.jobs.>",
          "aether.events.>",
          "aether.live.>",
          "aether.dlq.>",
          "aether.state.>",
          "aether.monitoring.>",
          "aether.notify.>",
          "$$JS.API.>",
          "$$JS.ACK.>",
          "$$JS.FC.>",
          "$$KV.>",
          "_INBOX.>"
        ]
        subscribe: [
          "aether.jobs.>",
          "aether.events.>",
          "aether.live.>",
          "aether.dlq.>",
          "aether.state.>",
          "aether.monitoring.>",
          "aether.notify.>",
          "$$JS.API.>",
          "$$JS.ACK.>",
          "$$JS.FC.>",
          "$$KV.>",
          "_INBOX.>"
        ]
      }
    }
  ]
}
