import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiNestjs,
  SiFastapi,
  SiGo,
  SiRust,
  SiNodedotjs,
  SiPython,
  SiDocker,
  SiPostgresql,
  SiMysql,
  SiMariadb,
  SiMongodb,
  SiRedis,
  SiRabbitmq,
  SiApachekafka,
  SiClickhouse,
  SiMeilisearch,
  SiElasticsearch,
  SiMinio,
  SiInfluxdb,
  SiWordpress,
  SiGhost,
  SiStrapi,
  SiDirectus,
  SiGrafana,
  SiPrometheus,
  SiUptimekuma,
  SiNetdata,
  SiMetabase,
  SiOllama,
  SiGitea,
  SiJenkins,
  SiJupyter,
  SiGitlab,
  SiAuthentik,
  SiKeycloak,
  SiVault,
  SiJellyfin,
  SiN8N,
  SiNodered,
  SiApacheairflow,
  SiCaddy,
  SiNginx,
  SiWireguard,
  SiAdguard,
  SiNextcloud,
  SiSearxng,
  SiBookstack,
  SiHomeassistant,
  SiPortainer,
  SiMattermost,
  SiRocketdotchat,
  SiOdoo,
  SiNginx as SiNginxStatic,
  SiTailscale,
  SiCloudflare,
  SiSupabase,
  SiForgejo,
  SiApache,
  SiUmami,
  SiPlausibleanalytics,
  SiPhpmyadmin,
  SiMatrix,
  SiElement,
  SiCaldotcom,
  SiLangchain,
  SiFireflyiii,
} from "react-icons/si";

const MAP: Record<string, IconType> = {
  react: SiReact,
  nextjs: SiNextdotjs,
  next: SiNextdotjs,
  nestjs: SiNestjs,
  fastapi: SiFastapi,
  go: SiGo,
  rust: SiRust,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  python: SiPython,
  docker: SiDocker,
  dockerfile: SiDocker,
  image: SiDocker,
  oci: SiDocker,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mysql: SiMysql,
  mariadb: SiMariadb,
  sqlserver: SiMysql,
  mssql: SiMysql,
  oracle: SiMysql,
  mongodb: SiMongodb,
  mongo: SiMongodb,
  redis: SiRedis,
  valkey: SiRedis,
  rabbitmq: SiRabbitmq,
  kafka: SiApachekafka,
  clickhouse: SiClickhouse,
  meilisearch: SiMeilisearch,
  elasticsearch: SiElasticsearch,
  minio: SiMinio,
  influxdb: SiInfluxdb,
  wordpress: SiWordpress,
  ghost: SiGhost,
  strapi: SiStrapi,
  directus: SiDirectus,
  grafana: SiGrafana,
  "grafana-oncall": SiGrafana,
  prometheus: SiPrometheus,
  "uptime-kuma": SiUptimekuma,
  netdata: SiNetdata,
  loki: SiGrafana,
  metabase: SiMetabase,
  superset: SiApache,
  umami: SiUmami,
  plausible: SiPlausibleanalytics,
  ollama: SiOllama,
  gitea: SiGitea,
  forgejo: SiForgejo,
  "code-server": SiNodedotjs,
  jenkins: SiJenkins,
  jupyterlab: SiJupyter,
  gitlab: SiGitlab,
  authentik: SiAuthentik,
  keycloak: SiKeycloak,
  vault: SiVault,
  jellyfin: SiJellyfin,
  n8n: SiN8N,
  nodered: SiNodered,
  airflow: SiApacheairflow,
  caddy: SiCaddy,
  "nginx-proxy": SiNginx,
  "nginx-static": SiNginxStatic,
  "wg-easy": SiWireguard,
  adguard: SiAdguard,
  nextcloud: SiNextcloud,
  searxng: SiSearxng,
  bookstack: SiBookstack,
  "home-assistant": SiHomeassistant,
  portainer: SiPortainer,
  mattermost: SiMattermost,
  "rocket-chat": SiRocketdotchat,
  odoo: SiOdoo,
  tailscale: SiTailscale,
  cloudflared: SiCloudflare,
  supabase: SiSupabase,
  "postgres-admin": SiPostgresql,
  phpmyadmin: SiPhpmyadmin,
  matrix: SiMatrix,
  element: SiElement,
  calcom: SiCaldotcom,
  langflow: SiLangchain,
  firefly: SiFireflyiii,
};

export function TechIcon({ name, size = 20, className = "" }: { name?: string; size?: number; className?: string }) {
  const key = (name ?? "").toLowerCase();
  const Icon = MAP[key];
  if (Icon) {
    return <Icon size={size} className={className} aria-hidden="true" />;
  }
  const initial = (name || "?").slice(0, 1).toUpperCase();
  return (
    <span
      aria-hidden="true"
      style={{ width: size, height: size, fontSize: size * 0.62, lineHeight: `${size}px` }}
      className={`inline-flex items-center justify-center rounded-full bg-primary/15 text-primary font-semibold select-none ${className}`}
    >
      {initial}
    </span>
  );
}
