/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as StudioDatabaseIdRouteImport } from './routes/studio/$databaseId'
import { Route as ShellAppsIndexRouteImport } from './routes/_shell/apps/index'
import { Route as ShellAppsAppIdRouteImport } from './routes/_shell/apps/$appId'
import { Route as ShellDatabasesIndexRouteImport } from './routes/_shell/databases/index'
import { Route as ShellDatabasesDbIdRouteImport } from './routes/_shell/databases/$dbId'
import { Route as ShellMembersIndexRouteImport } from './routes/_shell/members/index'
import { Route as ShellMonitoringIndexRouteImport } from './routes/_shell/monitoring/index'
import { Route as ShellNetworkingIndexRouteImport } from './routes/_shell/networking/index'
import { Route as ShellNotificationsIndexRouteImport } from './routes/_shell/notifications/index'
import { Route as ShellProjectsIndexRouteImport } from './routes/_shell/projects/index'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell/projects/$projectId'
import { Route as ShellProjectsNewRouteImport } from './routes/_shell/projects/new'
import { Route as ShellRegistryIndexRouteImport } from './routes/_shell/registry/index'
import { Route as ShellServicesIndexRouteImport } from './routes/_shell/services/index'
import { Route as ShellServicesServiceIdRouteImport } from './routes/_shell/services/$serviceId'
import { Route as ShellServicesNewRouteImport } from './routes/_shell/services/new'
import { Route as ShellStorageIndexRouteImport } from './routes/_shell/storage/index'
import { Route as ShellTraefikIndexRouteImport } from './routes/_shell/traefik/index'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDatabaseIdRoute = StudioDatabaseIdRouteImport.update({
  id: '/studio/$databaseId',
  path: '/studio/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAppsIndexRoute = ShellAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppsAppIdRoute = ShellAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesIndexRoute = ShellDatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesDbIdRoute = ShellDatabasesDbIdRouteImport.update({
  id: '/databases/$dbId',
  path: '/databases/$dbId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersIndexRoute = ShellMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitoringIndexRoute = ShellMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNetworkingIndexRoute = ShellNetworkingIndexRouteImport.update({
  id: '/networking/',
  path: '/networking/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsIndexRoute = ShellNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsIndexRoute = ShellProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsNewRoute = ShellProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRegistryIndexRoute = ShellRegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServicesIndexRoute = ShellServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServicesServiceIdRoute = ShellServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServicesNewRoute = ShellServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStorageIndexRoute = ShellStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTraefikIndexRoute = ShellTraefikIndexRouteImport.update({
  id: '/traefik/',
  path: '/traefik/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/studio/$databaseId': typeof StudioDatabaseIdRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/apps/$appId': typeof ShellAppsAppIdRoute
  '/databases/$dbId': typeof ShellDatabasesDbIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
  '/services/$serviceId': typeof ShellServicesServiceIdRoute
  '/services/new': typeof ShellServicesNewRoute
  '/apps/': typeof ShellAppsIndexRoute
  '/databases/': typeof ShellDatabasesIndexRoute
  '/members/': typeof ShellMembersIndexRoute
  '/monitoring/': typeof ShellMonitoringIndexRoute
  '/networking/': typeof ShellNetworkingIndexRoute
  '/notifications/': typeof ShellNotificationsIndexRoute
  '/projects/': typeof ShellProjectsIndexRoute
  '/registry/': typeof ShellRegistryIndexRoute
  '/services/': typeof ShellServicesIndexRoute
  '/storage/': typeof ShellStorageIndexRoute
  '/traefik/': typeof ShellTraefikIndexRoute
}
export interface FileRoutesByTo {
  '/studio/$databaseId': typeof StudioDatabaseIdRoute
  '/': typeof ShellIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/apps/$appId': typeof ShellAppsAppIdRoute
  '/databases/$dbId': typeof ShellDatabasesDbIdRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/projects/new': typeof ShellProjectsNewRoute
  '/services/$serviceId': typeof ShellServicesServiceIdRoute
  '/services/new': typeof ShellServicesNewRoute
  '/apps': typeof ShellAppsIndexRoute
  '/databases': typeof ShellDatabasesIndexRoute
  '/members': typeof ShellMembersIndexRoute
  '/monitoring': typeof ShellMonitoringIndexRoute
  '/networking': typeof ShellNetworkingIndexRoute
  '/notifications': typeof ShellNotificationsIndexRoute
  '/projects': typeof ShellProjectsIndexRoute
  '/registry': typeof ShellRegistryIndexRoute
  '/services': typeof ShellServicesIndexRoute
  '/storage': typeof ShellStorageIndexRoute
  '/traefik': typeof ShellTraefikIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/studio/$databaseId': typeof StudioDatabaseIdRoute
  '/_shell/': typeof ShellIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_shell/apps/$appId': typeof ShellAppsAppIdRoute
  '/_shell/databases/$dbId': typeof ShellDatabasesDbIdRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/projects/new': typeof ShellProjectsNewRoute
  '/_shell/services/$serviceId': typeof ShellServicesServiceIdRoute
  '/_shell/services/new': typeof ShellServicesNewRoute
  '/_shell/apps/': typeof ShellAppsIndexRoute
  '/_shell/databases/': typeof ShellDatabasesIndexRoute
  '/_shell/members/': typeof ShellMembersIndexRoute
  '/_shell/monitoring/': typeof ShellMonitoringIndexRoute
  '/_shell/networking/': typeof ShellNetworkingIndexRoute
  '/_shell/notifications/': typeof ShellNotificationsIndexRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
  '/_shell/registry/': typeof ShellRegistryIndexRoute
  '/_shell/services/': typeof ShellServicesIndexRoute
  '/_shell/storage/': typeof ShellStorageIndexRoute
  '/_shell/traefik/': typeof ShellTraefikIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio/$databaseId'
    | '/login/'
    | '/onboarding/'
    | '/apps/$appId'
    | '/databases/$dbId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/apps/'
    | '/databases/'
    | '/members/'
    | '/monitoring/'
    | '/networking/'
    | '/notifications/'
    | '/projects/'
    | '/registry/'
    | '/services/'
    | '/storage/'
    | '/traefik/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio/$databaseId'
    | '/'
    | '/login'
    | '/onboarding'
    | '/apps/$appId'
    | '/databases/$dbId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/services/$serviceId'
    | '/services/new'
    | '/apps'
    | '/databases'
    | '/members'
    | '/monitoring'
    | '/networking'
    | '/notifications'
    | '/projects'
    | '/registry'
    | '/services'
    | '/storage'
    | '/traefik'
  id:
    | '__root__'
    | '/_shell'
    | '/studio/$databaseId'
    | '/_shell/'
    | '/login/'
    | '/onboarding/'
    | '/_shell/apps/$appId'
    | '/_shell/databases/$dbId'
    | '/_shell/projects/$projectId'
    | '/_shell/projects/new'
    | '/_shell/services/$serviceId'
    | '/_shell/services/new'
    | '/_shell/apps/'
    | '/_shell/databases/'
    | '/_shell/members/'
    | '/_shell/monitoring/'
    | '/_shell/networking/'
    | '/_shell/notifications/'
    | '/_shell/projects/'
    | '/_shell/registry/'
    | '/_shell/services/'
    | '/_shell/storage/'
    | '/_shell/traefik/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  StudioDatabaseIdRoute: typeof StudioDatabaseIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$databaseId': {
      id: '/studio/$databaseId'
      path: '/studio/$databaseId'
      fullPath: '/studio/$databaseId'
      preLoaderRoute: typeof StudioDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/apps/': {
      id: '/_shell/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ShellAppsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/apps/$appId': {
      id: '/_shell/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof ShellAppsAppIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases/': {
      id: '/_shell/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof ShellDatabasesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases/$dbId': {
      id: '/_shell/databases/$dbId'
      path: '/databases/$dbId'
      fullPath: '/databases/$dbId'
      preLoaderRoute: typeof ShellDatabasesDbIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members/': {
      id: '/_shell/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof ShellMembersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitoring/': {
      id: '/_shell/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof ShellMonitoringIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/networking/': {
      id: '/_shell/networking/'
      path: '/networking'
      fullPath: '/networking/'
      preLoaderRoute: typeof ShellNetworkingIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications/': {
      id: '/_shell/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ShellNotificationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/': {
      id: '/_shell/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ShellProjectsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/new': {
      id: '/_shell/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ShellProjectsNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/registry/': {
      id: '/_shell/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof ShellRegistryIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/services/': {
      id: '/_shell/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ShellServicesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/services/$serviceId': {
      id: '/_shell/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ShellServicesServiceIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/services/new': {
      id: '/_shell/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ShellServicesNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/storage/': {
      id: '/_shell/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof ShellStorageIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/traefik/': {
      id: '/_shell/traefik/'
      path: '/traefik'
      fullPath: '/traefik/'
      preLoaderRoute: typeof ShellTraefikIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAppsAppIdRoute: typeof ShellAppsAppIdRoute
  ShellDatabasesDbIdRoute: typeof ShellDatabasesDbIdRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellProjectsNewRoute: typeof ShellProjectsNewRoute
  ShellServicesServiceIdRoute: typeof ShellServicesServiceIdRoute
  ShellServicesNewRoute: typeof ShellServicesNewRoute
  ShellAppsIndexRoute: typeof ShellAppsIndexRoute
  ShellDatabasesIndexRoute: typeof ShellDatabasesIndexRoute
  ShellMembersIndexRoute: typeof ShellMembersIndexRoute
  ShellMonitoringIndexRoute: typeof ShellMonitoringIndexRoute
  ShellNetworkingIndexRoute: typeof ShellNetworkingIndexRoute
  ShellNotificationsIndexRoute: typeof ShellNotificationsIndexRoute
  ShellProjectsIndexRoute: typeof ShellProjectsIndexRoute
  ShellRegistryIndexRoute: typeof ShellRegistryIndexRoute
  ShellServicesIndexRoute: typeof ShellServicesIndexRoute
  ShellStorageIndexRoute: typeof ShellStorageIndexRoute
  ShellTraefikIndexRoute: typeof ShellTraefikIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellAppsAppIdRoute: ShellAppsAppIdRoute,
  ShellDatabasesDbIdRoute: ShellDatabasesDbIdRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellProjectsNewRoute: ShellProjectsNewRoute,
  ShellServicesServiceIdRoute: ShellServicesServiceIdRoute,
  ShellServicesNewRoute: ShellServicesNewRoute,
  ShellAppsIndexRoute: ShellAppsIndexRoute,
  ShellDatabasesIndexRoute: ShellDatabasesIndexRoute,
  ShellMembersIndexRoute: ShellMembersIndexRoute,
  ShellMonitoringIndexRoute: ShellMonitoringIndexRoute,
  ShellNetworkingIndexRoute: ShellNetworkingIndexRoute,
  ShellNotificationsIndexRoute: ShellNotificationsIndexRoute,
  ShellProjectsIndexRoute: ShellProjectsIndexRoute,
  ShellRegistryIndexRoute: ShellRegistryIndexRoute,
  ShellServicesIndexRoute: ShellServicesIndexRoute,
  ShellStorageIndexRoute: ShellStorageIndexRoute,
  ShellTraefikIndexRoute: ShellTraefikIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  StudioDatabaseIdRoute: StudioDatabaseIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
