/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as ShellApiKeysIndexRouteImport } from './routes/_shell/api-keys/index'
import { Route as ShellAppsIndexRouteImport } from './routes/_shell/apps/index'
import { Route as ShellBackupsIndexRouteImport } from './routes/_shell/backups/index'
import { Route as ShellCertificatesIndexRouteImport } from './routes/_shell/certificates/index'
import { Route as ShellCiCdIndexRouteImport } from './routes/_shell/ci-cd/index'
import { Route as ShellClustersIndexRouteImport } from './routes/_shell/clusters/index'
import { Route as ShellComposeIdRouteImport } from './routes/_shell/compose.$id'
import { Route as ShellDatabasesIndexRouteImport } from './routes/_shell/databases/index'
import { Route as ShellGitopsIndexRouteImport } from './routes/_shell/gitops/index'
import { Route as ShellMarketplaceIndexRouteImport } from './routes/_shell/marketplace/index'
import { Route as ShellMembersIndexRouteImport } from './routes/_shell/members/index'
import { Route as ShellMonitoringIndexRouteImport } from './routes/_shell/monitoring/index'
import { Route as ShellNetworkingIndexRouteImport } from './routes/_shell/networking/index'
import { Route as ShellNotificationsIndexRouteImport } from './routes/_shell/notifications/index'
import { Route as ShellProjectsIndexRouteImport } from './routes/_shell/projects/index'
import { Route as ShellRegistryIndexRouteImport } from './routes/_shell/registry/index'
import { Route as ShellSchedulesIndexRouteImport } from './routes/_shell/schedules/index'
import { Route as ShellSecretsIndexRouteImport } from './routes/_shell/secrets/index'
import { Route as ShellServersIndexRouteImport } from './routes/_shell/servers/index'
import { Route as ShellSsoIndexRouteImport } from './routes/_shell/sso/index'
import { Route as ShellStorageIndexRouteImport } from './routes/_shell/storage/index'
import { Route as ShellWhitelabelIndexRouteImport } from './routes/_shell/whitelabel/index'
import { Route as StudioDbIdIndexRouteImport } from './routes/studio.$dbId/index'
import { Route as ShellAppsAppIdIndexRouteImport } from './routes/_shell/apps.$appId/index'
import { Route as ShellDatabasesDbIdIndexRouteImport } from './routes/_shell/databases.$dbId/index'
import { Route as ShellProjectsProjectIdIndexRouteImport } from './routes/_shell/projects.$projectId/index'
import { Route as ShellProjectsNewIndexRouteImport } from './routes/_shell/projects.new/index'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellApiKeysIndexRoute = ShellApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppsIndexRoute = ShellAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBackupsIndexRoute = ShellBackupsIndexRouteImport.update({
  id: '/backups/',
  path: '/backups/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCertificatesIndexRoute = ShellCertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCiCdIndexRoute = ShellCiCdIndexRouteImport.update({
  id: '/ci-cd/',
  path: '/ci-cd/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClustersIndexRoute = ShellClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComposeIdRoute = ShellComposeIdRouteImport.update({
  id: '/compose/$id',
  path: '/compose/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesIndexRoute = ShellDatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGitopsIndexRoute = ShellGitopsIndexRouteImport.update({
  id: '/gitops/',
  path: '/gitops/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMarketplaceIndexRoute = ShellMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembersIndexRoute = ShellMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMonitoringIndexRoute = ShellMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNetworkingIndexRoute = ShellNetworkingIndexRouteImport.update({
  id: '/networking/',
  path: '/networking/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsIndexRoute = ShellNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsIndexRoute = ShellProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRegistryIndexRoute = ShellRegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSchedulesIndexRoute = ShellSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSecretsIndexRoute = ShellSecretsIndexRouteImport.update({
  id: '/secrets/',
  path: '/secrets/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServersIndexRoute = ShellServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSsoIndexRoute = ShellSsoIndexRouteImport.update({
  id: '/sso/',
  path: '/sso/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStorageIndexRoute = ShellStorageIndexRouteImport.update({
  id: '/storage/',
  path: '/storage/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWhitelabelIndexRoute = ShellWhitelabelIndexRouteImport.update({
  id: '/whitelabel/',
  path: '/whitelabel/',
  getParentRoute: () => ShellRoute,
} as any)
const StudioDbIdIndexRoute = StudioDbIdIndexRouteImport.update({
  id: '/studio/$dbId/',
  path: '/studio/$dbId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/studio.$dbId/index.lazy').then((d) => d.Route),
)
const ShellAppsAppIdIndexRoute = ShellAppsAppIdIndexRouteImport.update({
  id: '/apps/$appId/',
  path: '/apps/$appId/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesDbIdIndexRoute = ShellDatabasesDbIdIndexRouteImport.update({
  id: '/databases/$dbId/',
  path: '/databases/$dbId/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdIndexRoute =
  ShellProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsNewIndexRoute = ShellProjectsNewIndexRouteImport.update({
  id: '/projects/new/',
  path: '/projects/new/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/compose/$id': typeof ShellComposeIdRoute
  '/api-keys/': typeof ShellApiKeysIndexRoute
  '/apps/': typeof ShellAppsIndexRoute
  '/backups/': typeof ShellBackupsIndexRoute
  '/certificates/': typeof ShellCertificatesIndexRoute
  '/ci-cd/': typeof ShellCiCdIndexRoute
  '/clusters/': typeof ShellClustersIndexRoute
  '/databases/': typeof ShellDatabasesIndexRoute
  '/gitops/': typeof ShellGitopsIndexRoute
  '/marketplace/': typeof ShellMarketplaceIndexRoute
  '/members/': typeof ShellMembersIndexRoute
  '/monitoring/': typeof ShellMonitoringIndexRoute
  '/networking/': typeof ShellNetworkingIndexRoute
  '/notifications/': typeof ShellNotificationsIndexRoute
  '/projects/': typeof ShellProjectsIndexRoute
  '/registry/': typeof ShellRegistryIndexRoute
  '/schedules/': typeof ShellSchedulesIndexRoute
  '/secrets/': typeof ShellSecretsIndexRoute
  '/servers/': typeof ShellServersIndexRoute
  '/sso/': typeof ShellSsoIndexRoute
  '/storage/': typeof ShellStorageIndexRoute
  '/whitelabel/': typeof ShellWhitelabelIndexRoute
  '/studio/$dbId/': typeof StudioDbIdIndexRoute
  '/apps/$appId/': typeof ShellAppsAppIdIndexRoute
  '/databases/$dbId/': typeof ShellDatabasesDbIdIndexRoute
  '/projects/$projectId/': typeof ShellProjectsProjectIdIndexRoute
  '/projects/new/': typeof ShellProjectsNewIndexRoute
}
export interface FileRoutesByTo {
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/': typeof ShellIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/compose/$id': typeof ShellComposeIdRoute
  '/api-keys': typeof ShellApiKeysIndexRoute
  '/apps': typeof ShellAppsIndexRoute
  '/backups': typeof ShellBackupsIndexRoute
  '/certificates': typeof ShellCertificatesIndexRoute
  '/ci-cd': typeof ShellCiCdIndexRoute
  '/clusters': typeof ShellClustersIndexRoute
  '/databases': typeof ShellDatabasesIndexRoute
  '/gitops': typeof ShellGitopsIndexRoute
  '/marketplace': typeof ShellMarketplaceIndexRoute
  '/members': typeof ShellMembersIndexRoute
  '/monitoring': typeof ShellMonitoringIndexRoute
  '/networking': typeof ShellNetworkingIndexRoute
  '/notifications': typeof ShellNotificationsIndexRoute
  '/projects': typeof ShellProjectsIndexRoute
  '/registry': typeof ShellRegistryIndexRoute
  '/schedules': typeof ShellSchedulesIndexRoute
  '/secrets': typeof ShellSecretsIndexRoute
  '/servers': typeof ShellServersIndexRoute
  '/sso': typeof ShellSsoIndexRoute
  '/storage': typeof ShellStorageIndexRoute
  '/whitelabel': typeof ShellWhitelabelIndexRoute
  '/studio/$dbId': typeof StudioDbIdIndexRoute
  '/apps/$appId': typeof ShellAppsAppIdIndexRoute
  '/databases/$dbId': typeof ShellDatabasesDbIdIndexRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdIndexRoute
  '/projects/new': typeof ShellProjectsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/organizations/$id': typeof OrganizationsIdRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/_shell/': typeof ShellIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_shell/compose/$id': typeof ShellComposeIdRoute
  '/_shell/api-keys/': typeof ShellApiKeysIndexRoute
  '/_shell/apps/': typeof ShellAppsIndexRoute
  '/_shell/backups/': typeof ShellBackupsIndexRoute
  '/_shell/certificates/': typeof ShellCertificatesIndexRoute
  '/_shell/ci-cd/': typeof ShellCiCdIndexRoute
  '/_shell/clusters/': typeof ShellClustersIndexRoute
  '/_shell/databases/': typeof ShellDatabasesIndexRoute
  '/_shell/gitops/': typeof ShellGitopsIndexRoute
  '/_shell/marketplace/': typeof ShellMarketplaceIndexRoute
  '/_shell/members/': typeof ShellMembersIndexRoute
  '/_shell/monitoring/': typeof ShellMonitoringIndexRoute
  '/_shell/networking/': typeof ShellNetworkingIndexRoute
  '/_shell/notifications/': typeof ShellNotificationsIndexRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
  '/_shell/registry/': typeof ShellRegistryIndexRoute
  '/_shell/schedules/': typeof ShellSchedulesIndexRoute
  '/_shell/secrets/': typeof ShellSecretsIndexRoute
  '/_shell/servers/': typeof ShellServersIndexRoute
  '/_shell/sso/': typeof ShellSsoIndexRoute
  '/_shell/storage/': typeof ShellStorageIndexRoute
  '/_shell/whitelabel/': typeof ShellWhitelabelIndexRoute
  '/studio/$dbId/': typeof StudioDbIdIndexRoute
  '/_shell/apps/$appId/': typeof ShellAppsAppIdIndexRoute
  '/_shell/databases/$dbId/': typeof ShellDatabasesDbIdIndexRoute
  '/_shell/projects/$projectId/': typeof ShellProjectsProjectIdIndexRoute
  '/_shell/projects/new/': typeof ShellProjectsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizations/$id'
    | '/organizations/new'
    | '/login/'
    | '/onboarding/'
    | '/compose/$id'
    | '/api-keys/'
    | '/apps/'
    | '/backups/'
    | '/certificates/'
    | '/ci-cd/'
    | '/clusters/'
    | '/databases/'
    | '/gitops/'
    | '/marketplace/'
    | '/members/'
    | '/monitoring/'
    | '/networking/'
    | '/notifications/'
    | '/projects/'
    | '/registry/'
    | '/schedules/'
    | '/secrets/'
    | '/servers/'
    | '/sso/'
    | '/storage/'
    | '/whitelabel/'
    | '/studio/$dbId/'
    | '/apps/$appId/'
    | '/databases/$dbId/'
    | '/projects/$projectId/'
    | '/projects/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/organizations/$id'
    | '/organizations/new'
    | '/'
    | '/login'
    | '/onboarding'
    | '/compose/$id'
    | '/api-keys'
    | '/apps'
    | '/backups'
    | '/certificates'
    | '/ci-cd'
    | '/clusters'
    | '/databases'
    | '/gitops'
    | '/marketplace'
    | '/members'
    | '/monitoring'
    | '/networking'
    | '/notifications'
    | '/projects'
    | '/registry'
    | '/schedules'
    | '/secrets'
    | '/servers'
    | '/sso'
    | '/storage'
    | '/whitelabel'
    | '/studio/$dbId'
    | '/apps/$appId'
    | '/databases/$dbId'
    | '/projects/$projectId'
    | '/projects/new'
  id:
    | '__root__'
    | '/_shell'
    | '/organizations/$id'
    | '/organizations/new'
    | '/_shell/'
    | '/login/'
    | '/onboarding/'
    | '/_shell/compose/$id'
    | '/_shell/api-keys/'
    | '/_shell/apps/'
    | '/_shell/backups/'
    | '/_shell/certificates/'
    | '/_shell/ci-cd/'
    | '/_shell/clusters/'
    | '/_shell/databases/'
    | '/_shell/gitops/'
    | '/_shell/marketplace/'
    | '/_shell/members/'
    | '/_shell/monitoring/'
    | '/_shell/networking/'
    | '/_shell/notifications/'
    | '/_shell/projects/'
    | '/_shell/registry/'
    | '/_shell/schedules/'
    | '/_shell/secrets/'
    | '/_shell/servers/'
    | '/_shell/sso/'
    | '/_shell/storage/'
    | '/_shell/whitelabel/'
    | '/studio/$dbId/'
    | '/_shell/apps/$appId/'
    | '/_shell/databases/$dbId/'
    | '/_shell/projects/$projectId/'
    | '/_shell/projects/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  StudioDbIdIndexRoute: typeof StudioDbIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/api-keys/': {
      id: '/_shell/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof ShellApiKeysIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/apps/': {
      id: '/_shell/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ShellAppsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/backups/': {
      id: '/_shell/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof ShellBackupsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/certificates/': {
      id: '/_shell/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof ShellCertificatesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ci-cd/': {
      id: '/_shell/ci-cd/'
      path: '/ci-cd'
      fullPath: '/ci-cd/'
      preLoaderRoute: typeof ShellCiCdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clusters/': {
      id: '/_shell/clusters/'
      path: '/clusters'
      fullPath: '/clusters/'
      preLoaderRoute: typeof ShellClustersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/compose/$id': {
      id: '/_shell/compose/$id'
      path: '/compose/$id'
      fullPath: '/compose/$id'
      preLoaderRoute: typeof ShellComposeIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases/': {
      id: '/_shell/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof ShellDatabasesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/gitops/': {
      id: '/_shell/gitops/'
      path: '/gitops'
      fullPath: '/gitops/'
      preLoaderRoute: typeof ShellGitopsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marketplace/': {
      id: '/_shell/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof ShellMarketplaceIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/members/': {
      id: '/_shell/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof ShellMembersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/monitoring/': {
      id: '/_shell/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof ShellMonitoringIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/networking/': {
      id: '/_shell/networking/'
      path: '/networking'
      fullPath: '/networking/'
      preLoaderRoute: typeof ShellNetworkingIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications/': {
      id: '/_shell/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof ShellNotificationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/': {
      id: '/_shell/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ShellProjectsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/registry/': {
      id: '/_shell/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof ShellRegistryIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/schedules/': {
      id: '/_shell/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof ShellSchedulesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/secrets/': {
      id: '/_shell/secrets/'
      path: '/secrets'
      fullPath: '/secrets/'
      preLoaderRoute: typeof ShellSecretsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/servers/': {
      id: '/_shell/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ShellServersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sso/': {
      id: '/_shell/sso/'
      path: '/sso'
      fullPath: '/sso/'
      preLoaderRoute: typeof ShellSsoIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/storage/': {
      id: '/_shell/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof ShellStorageIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/whitelabel/': {
      id: '/_shell/whitelabel/'
      path: '/whitelabel'
      fullPath: '/whitelabel/'
      preLoaderRoute: typeof ShellWhitelabelIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/studio/$dbId/': {
      id: '/studio/$dbId/'
      path: '/studio/$dbId'
      fullPath: '/studio/$dbId/'
      preLoaderRoute: typeof StudioDbIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/apps/$appId/': {
      id: '/_shell/apps/$appId/'
      path: '/apps/$appId'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof ShellAppsAppIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases/$dbId/': {
      id: '/_shell/databases/$dbId/'
      path: '/databases/$dbId'
      fullPath: '/databases/$dbId/'
      preLoaderRoute: typeof ShellDatabasesDbIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId/': {
      id: '/_shell/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ShellProjectsProjectIdIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/new/': {
      id: '/_shell/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new/'
      preLoaderRoute: typeof ShellProjectsNewIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellComposeIdRoute: typeof ShellComposeIdRoute
  ShellApiKeysIndexRoute: typeof ShellApiKeysIndexRoute
  ShellAppsIndexRoute: typeof ShellAppsIndexRoute
  ShellBackupsIndexRoute: typeof ShellBackupsIndexRoute
  ShellCertificatesIndexRoute: typeof ShellCertificatesIndexRoute
  ShellCiCdIndexRoute: typeof ShellCiCdIndexRoute
  ShellClustersIndexRoute: typeof ShellClustersIndexRoute
  ShellDatabasesIndexRoute: typeof ShellDatabasesIndexRoute
  ShellGitopsIndexRoute: typeof ShellGitopsIndexRoute
  ShellMarketplaceIndexRoute: typeof ShellMarketplaceIndexRoute
  ShellMembersIndexRoute: typeof ShellMembersIndexRoute
  ShellMonitoringIndexRoute: typeof ShellMonitoringIndexRoute
  ShellNetworkingIndexRoute: typeof ShellNetworkingIndexRoute
  ShellNotificationsIndexRoute: typeof ShellNotificationsIndexRoute
  ShellProjectsIndexRoute: typeof ShellProjectsIndexRoute
  ShellRegistryIndexRoute: typeof ShellRegistryIndexRoute
  ShellSchedulesIndexRoute: typeof ShellSchedulesIndexRoute
  ShellSecretsIndexRoute: typeof ShellSecretsIndexRoute
  ShellServersIndexRoute: typeof ShellServersIndexRoute
  ShellSsoIndexRoute: typeof ShellSsoIndexRoute
  ShellStorageIndexRoute: typeof ShellStorageIndexRoute
  ShellWhitelabelIndexRoute: typeof ShellWhitelabelIndexRoute
  ShellAppsAppIdIndexRoute: typeof ShellAppsAppIdIndexRoute
  ShellDatabasesDbIdIndexRoute: typeof ShellDatabasesDbIdIndexRoute
  ShellProjectsProjectIdIndexRoute: typeof ShellProjectsProjectIdIndexRoute
  ShellProjectsNewIndexRoute: typeof ShellProjectsNewIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellComposeIdRoute: ShellComposeIdRoute,
  ShellApiKeysIndexRoute: ShellApiKeysIndexRoute,
  ShellAppsIndexRoute: ShellAppsIndexRoute,
  ShellBackupsIndexRoute: ShellBackupsIndexRoute,
  ShellCertificatesIndexRoute: ShellCertificatesIndexRoute,
  ShellCiCdIndexRoute: ShellCiCdIndexRoute,
  ShellClustersIndexRoute: ShellClustersIndexRoute,
  ShellDatabasesIndexRoute: ShellDatabasesIndexRoute,
  ShellGitopsIndexRoute: ShellGitopsIndexRoute,
  ShellMarketplaceIndexRoute: ShellMarketplaceIndexRoute,
  ShellMembersIndexRoute: ShellMembersIndexRoute,
  ShellMonitoringIndexRoute: ShellMonitoringIndexRoute,
  ShellNetworkingIndexRoute: ShellNetworkingIndexRoute,
  ShellNotificationsIndexRoute: ShellNotificationsIndexRoute,
  ShellProjectsIndexRoute: ShellProjectsIndexRoute,
  ShellRegistryIndexRoute: ShellRegistryIndexRoute,
  ShellSchedulesIndexRoute: ShellSchedulesIndexRoute,
  ShellSecretsIndexRoute: ShellSecretsIndexRoute,
  ShellServersIndexRoute: ShellServersIndexRoute,
  ShellSsoIndexRoute: ShellSsoIndexRoute,
  ShellStorageIndexRoute: ShellStorageIndexRoute,
  ShellWhitelabelIndexRoute: ShellWhitelabelIndexRoute,
  ShellAppsAppIdIndexRoute: ShellAppsAppIdIndexRoute,
  ShellDatabasesDbIdIndexRoute: ShellDatabasesDbIdIndexRoute,
  ShellProjectsProjectIdIndexRoute: ShellProjectsProjectIdIndexRoute,
  ShellProjectsNewIndexRoute: ShellProjectsNewIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OrganizationsIdRoute: OrganizationsIdRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  StudioDbIdIndexRoute: StudioDbIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
