export const qk = {
  me: ["me"] as const,
  members: ["members"] as const,
  keys: ["api-keys"] as const,
  composes: ["composes"] as const,
  projects: ["projects"] as const,
  services: ["services"] as const,
  apps: ["apps"] as const,
  app: (id: string) => ["app", id] as const,
  service: (id: string) => ["service", id] as const,
  serviceTimeline: (id: string) => ["service-timeline", id] as const,
  serviceStats: (id: string) => ["service-stats", id] as const,
  serviceDeployments: (id: string) => ["service-deployments", id] as const,
  serviceEnvironment: (id: string) => ["service-environment", id] as const,
  serviceContainers: (id: string) => ["service-containers", id] as const,
  deployments: (id: string) => ["deployments", id] as const,
  domains: (kind: string, id: string) => ["domains", kind, id] as const,
  timeline: (id: string) => ["timeline", id] as const,
  backups: ["backups"] as const,
  stats: (id: string) => ["stats", id] as const,
};
