version: "3.8"

services:
  blender:
    image: lscr.io/linuxserver/blender@sha256:ebf57305c6c32245107916cf1eeda7d675fe6c5c52ac6d41d0241c75fc127237
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    expose:
      - 3000
      - 3001
    restart: unless-stopped
    shm_size: 1gb
