version: "3.8"
services:
  bytebase:
    image: bytebase/bytebase@sha256:793b5abe5f2d3a82ad03a528638d38080146f4d29288d821660e9678ae381b54
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - PG_URL=postgres://postgres:${DB_PASSWORD}@bytebase-db:5432/bytebase
    volumes:
      - data:/var/opt/bytebase
    depends_on:
      - bytebase-db

  bytebase-db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bytebase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  data: {}
  db_data: {} 
