services:
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway@sha256:6331ba665773b348638d0542bf78ed8908f7088d7a5811424f1cc0adf64ac8b7
    restart: always
    expose:
      - 4983
    environment:
      PORT: "4983"
      STORE_PATH: "/app"
      MASTERPASS: ${MASTERPASS}
    volumes:
      - drizzle-gateway:/app

volumes:
  drizzle-gateway:
