version: "3.8"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    expose:
      - 8191
    restart: unless-stopped
