services:
  garage:
    image: dxflrs/garage:v2.0.0
    volumes:
      - garage-storage:/var/lib/garage
    restart: unless-stopped
    expose:
      - 3900
      - 3901
      - 3902
      - 3903
volumes:
  garage-storage: {}
