version: "3.8"
services:
  grist:
    image: gristlabs/grist@sha256:e511abbb192079100d4da123cce574457c0c65a73daa49a92a2dae8945d40558
    restart: unless-stopped
    expose:
      - 8484
    volumes:
      - grist_data:/persist
    environment:
      GRIST_DEFAULT_EMAIL: ${GRIST_DEFAULT_EMAIL:-}
      GRIST_SESSION_SECRET: ${GRIST_SESSION_SECRET:-}
      GRIST_SINGLE_ORG: ${GRIST_SINGLE_ORG:-}
      GRIST_HOME_INSTANCE: ${GRIST_HOME_INSTANCE:-}

volumes:
  grist_data:

