version: "3.8"

services:
  kavita:
    image: jvmilazz0/kavita@sha256:31181a32f0dda73cae68721867028a7253d57881b58bea5754cd9e578e75421a
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - TZ=${TZ}
    volumes:
      - kavita-config:/kavita/config
      - kavita-media:/manga
      - kavita-books:/books
      - kavita-comics:/comics

volumes:
  kavita-config:
  kavita-media:
  kavita-books:
  kavita-comics:
