version: "3.9"

services:
  backend:
    image: ghcr.io/leonmuscoden/letterfeed-backend@sha256:c5ba23e2111af44f7b9ef861aff4f28da7b64ca2607878a9b353e1c11ecf59d9
    restart: unless-stopped
    environment:
      LETTERFEED_APP_BASE_URL: ${LETTERFEED_APP_BASE_URL}
      LETTERFEED_BACKEND_URL: ${LETTERFEED_BACKEND_URL}
      LETTERFEED_DATABASE_URL: ${LETTERFEED_DATABASE_URL}
      LETTERFEED_IMAP_SERVER: ${LETTERFEED_IMAP_SERVER}
      LETTERFEED_IMAP_USERNAME: ${LETTERFEED_IMAP_USERNAME}
      LETTERFEED_IMAP_PASSWORD: ${LETTERFEED_IMAP_PASSWORD}
      LETTERFEED_SEARCH_FOLDER: ${LETTERFEED_SEARCH_FOLDER}
      LETTERFEED_MOVE_TO_FOLDER: ${LETTERFEED_MOVE_TO_FOLDER}
      LETTERFEED_MARK_AS_READ: ${LETTERFEED_MARK_AS_READ}
      LETTERFEED_EMAIL_CHECK_INTERVAL: ${LETTERFEED_EMAIL_CHECK_INTERVAL}
      LETTERFEED_AUTO_ADD_NEW_SENDERS: ${LETTERFEED_AUTO_ADD_NEW_SENDERS}
      LETTERFEED_SECRET_KEY: ${LETTERFEED_SECRET_KEY}
      LETTERFEED_AUTH_USERNAME: ${LETTERFEED_AUTH_USERNAME}
      LETTERFEED_AUTH_PASSWORD: ${LETTERFEED_AUTH_PASSWORD}
    volumes:
      - letterfeed_data:/data

  frontend:
    image: ghcr.io/leonmuscoden/letterfeed-frontend@sha256:c7f2770c6b8b1968a6aec49871d919e6d26a5c2b8fbbca49099a93e1a1c2a9bf
    restart: unless-stopped
    environment:
      LETTERFEED_APP_BASE_URL: ${LETTERFEED_APP_BASE_URL}
      LETTERFEED_BACKEND_URL: ${LETTERFEED_BACKEND_URL}
    expose:
      - 3000
    depends_on:
      - backend

volumes:
  letterfeed_data:
