version: "3.8"
services:
  linkding:
    image: sissbruecker/linkding@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ../files/linkding-data:/etc/linkding/data
