services:
  navidrome:
    image: deluan/navidrome@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
    restart: unless-stopped
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
    volumes:
      - navidrome-data:/data
      - navidrome-music:/music:ro
    expose:
      - 4533
volumes:
  navidrome-data: {}
  navidrome-music: {}
