[variables]
main_domain = "${domain}"
secret_base = "${base64:64}"
totp_key = "${base64:32}"

[[config.domains]]
serviceName = "plausible"
port = 8_000
host = "${main_domain}"

[config.env]
BASE_URL = "http://${main_domain}"
SECRET_KEY_BASE = "${secret_base}"
TOTP_VAULT_KEY = "${totp_key}="
