version: "3.8"
services:
  statping-ng:
    image: adamboutcher/statping-ng@sha256:e32bd2e50ca023f37b0650e1942d51cb9269a2caab11042bc0cc53fac0474a2b
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DB_CONN=sqlite
    volumes:
      - ../files/statping-ng:/app
    expose:
      - 8080
