services:
  trilium:
    image: zadam/trilium@sha256:a0b5a6a5fd7a64391ae6039bbcd5493151a77a1d5470ef5911923c64d0c232c0
    expose:
      - 8080
    restart: always
    volumes:
      - /root/trilium-backups:/home/node/trilium-data/backup
  
