import type { IconType } from "react-icons";
import {
  SiActualbudget,
  SiAdguard,
  SiApache,
  SiApacheairflow,
  SiApachecassandra,
  SiApachecouchdb,
  SiApachekafka,
  SiApachepulsar,
  SiApachesuperset,
  SiAppsmith,
  SiAppwrite,
  SiArangodb,
  SiAudiobookshelf,
  SiAuthelia,
  SiAuthentik,
  SiBitwarden,
  SiBookstack,
  SiBudibase,
  SiBun,
  SiCaddy,
  SiCaldotcom,
  SiCalibreweb,
  SiChangedetection,
  SiClickhouse,
  SiCloudflare,
  SiCockroachlabs,
  SiDeno,  SiDgraph,
  SiDify,
  SiDirectus,
  SiDocker,
  SiDotnet,
  SiDrupal,
  SiElasticsearch,
  SiElement,
  SiEmby,
  SiEnvoyproxy,
  SiEspressif,
  SiEtcd,
  SiDrone,
  SiFastapi,
  SiFireflyiii,
  SiFluentbit,
  SiForgejo,
  SiFreshrss,
  SiGhost,
  SiGitea,
  SiGitlab,
  SiGlance,
  SiGo,
  SiGrafana,
  SiHedgedoc,
  SiHomarr,
  SiHomeassistant,
  SiHomepage,
  SiImmich,
  SiInfluxdb,
  SiJaeger,
  SiJellyfin,
  SiJenkins,
  SiJitsi,
  SiJoomla,
  SiJoplin,
  SiJupyter,
  SiK6,
  SiKeycloak,
  SiKong,
  SiLangchain,
  SiMariadb,
  SiMatomo,
  SiMatrix,
  SiMattermost,
  SiMeilisearch,
  SiMetabase,
  SiMilvus,
  SiMinio,
  SiMlflow,
  SiMongodb,
  SiMysql,
  SiN8N,
  SiNatsdotio,
  SiNeo4J,
  SiNestjs,
  SiNetdata,
  SiNextcloud,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNodered,
  SiNtfy,
  SiOctoprint,
  SiOdoo,
  SiOllama,
  SiOpenhab,
  SiOpensearch,
  SiOpenvpn,
  SiOutline,
  SiPaperlessngx,
  SiPayloadcms,
  SiPhp,
  SiPhpmyadmin,
  SiPihole,
  SiPlausibleanalytics,
  SiPlex,
  SiPortainer,
  SiPostgresql,
  SiPosthog,
  SiPrefect,
  SiPrometheus,
  SiPython,
  SiQbittorrent,
  SiQdrant,
  SiRabbitmq,
  SiRadarr,
  SiRclone,
  SiReact,
  SiRedash,
  SiRedis,
  SiRocketdotchat,
  SiRuby,
  SiRust,
  SiSeafile,
  SiSearxng,
  SiSentry,
  SiSonarr,
  SiSpeedtest,
  SiStrapi,
  SiSupabase,
  SiSurrealdb,
  SiSyncthing,
  SiTailscale,
  SiTimescale,
  SiTraefikproxy,
  SiTransmission,
  SiUmami,
  SiUptimekuma,
  SiVault,
  SiVikunja,
  SiWallabag,
  SiWireguard,
  SiWordpress,
  SiZigbee2Mqtt,
  SiZulip,
} from "react-icons/si";

const MAP: Record<string, IconType> = {
  "postgres": SiPostgresql,
  "mysql": SiMysql,
  "mariadb": SiMariadb,
  "mongodb": SiMongodb,
  "redis": SiRedis,
  "valkey": SiRedis,
  "clickhouse": SiClickhouse,
  "cockroachdb": SiCockroachlabs,
  "cassandra": SiApachecassandra,
  "neo4j": SiNeo4J,
  "surrealdb": SiSurrealdb,
  "arangodb": SiArangodb,
  "couchdb": SiApachecouchdb,
  "influxdb": SiInfluxdb,
  "timescaledb": SiTimescale,
  "etcd": SiEtcd,
  "opensearch": SiOpensearch,
  "elasticsearch": SiElasticsearch,
  "meilisearch": SiMeilisearch,
  "qdrant": SiQdrant,
  "milvus": SiMilvus,
  "dgraph": SiDgraph,
  "minio": SiMinio,
  "rabbitmq": SiRabbitmq,
  "kafka": SiApachekafka,
  "nats": SiNatsdotio,
  "pulsar": SiApachepulsar,
  "nginx": SiNginx,
  "caddy": SiCaddy,
  "traefik": SiTraefikproxy,
  "apache": SiApache,
  "envoy": SiEnvoyproxy,
  "node": SiNodedotjs,
  "python": SiPython,
  "golang": SiGo,
  "php": SiPhp,
  "ruby": SiRuby,
  "deno": SiDeno,
  "bun": SiBun,
  "dotnet": SiDotnet,
  "grafana": SiGrafana,
  "prometheus": SiPrometheus,
  "loki": SiGrafana,
  "tempo": SiGrafana,
  "uptime-kuma": SiUptimekuma,
  "netdata": SiNetdata,
  "agent": SiGrafana,
  "filebeat": SiElasticsearch,
  "jaeger": SiJaeger,
  "k6": SiK6,
  "fluent-bit": SiFluentbit,
  "wordpress": SiWordpress,
  "ghost": SiGhost,
  "strapi": SiStrapi,
  "directus": SiDirectus,
  "payload": SiPayloadcms,
  "drupal": SiDrupal,
  "joomla": SiJoomla,
  "bookstack": SiBookstack,
  "outline": SiOutline,
  "appwrite": SiAppwrite,
  "supabase": SiSupabase,
  "ollama": SiOllama,
  "n8n": SiN8N,
  "dify": SiDify,
  "langflow": SiLangchain,
  "posthog": SiPosthog,
  "mattermost": SiMattermost,
  "rocketchat": SiRocketdotchat,
  "zulip": SiZulip,
  "nextcloud": SiNextcloud,
  "seafile": SiSeafile,
  "paperless": SiPaperlessngx,
  "gitea": SiGitea,
  "forgejo": SiForgejo,
  "gitlab": SiGitlab,
  "jitsi": SiJitsi,
  "vaultwarden": SiBitwarden,
  "keycloak": SiKeycloak,
  "authentik": SiAuthentik,
  "authelia": SiAuthelia,
  "vault": SiVault,
  "openvpn": SiOpenvpn,
  "pihole": SiPihole,
  "adguard": SiAdguard,
  "syncthing": SiSyncthing,
  "rclone": SiRclone,
  "jellyfin": SiJellyfin,
  "plex": SiPlex,
  "emby": SiEmby,
  "sonarr": SiSonarr,
  "radarr": SiRadarr,
  "qbittorrent": SiQbittorrent,
  "transmission": SiTransmission,
  "immich-server": SiImmich,
  "audiobookshelf": SiAudiobookshelf,
  "homeassistant": SiHomeassistant,
  "node-red": SiNodered,
  "zigbee2mqtt": SiZigbee2Mqtt,
  "esphome": SiEspressif,
  "openhab": SiOpenhab,
  "metabase": SiMetabase,
  "redash": SiRedash,
  "superset": SiApachesuperset,
  "umami": SiUmami,
  "plausible": SiPlausibleanalytics,
  "matomo": SiMatomo,
  "airflow": SiApacheairflow,
  "prefect": SiPrefect,
  "jupyter": SiJupyter,
  "mlflow": SiMlflow,
  "dolphinscheduler": SiApacheairflow,
  "sentry": SiSentry,
  "console": SiMinio,
  "phpmyadmin": SiPhpmyadmin,
  "appsmith": SiAppsmith,
  "budibase": SiBudibase,
  "kong": SiKong,
  "faro": SiGrafana,
  "homepage": SiHomepage,
  "homarr": SiHomarr,
  "glance": SiGlance,
  "wallabag": SiWallabag,
  "freshrss": SiFreshrss,
  "ttrss": SiFreshrss,
  "calibre-web": SiCalibreweb,
  "vikunja": SiVikunja,
  "changedetection": SiChangedetection,
  "speedtest": SiSpeedtest,
  "ntfy": SiNtfy,
  "react": SiReact,
  "nextjs": SiNextdotjs,
  "next": SiNextdotjs,
  "nestjs": SiNestjs,
  "fastapi": SiFastapi,
  "go": SiGo,
  "rust": SiRust,
  "nodejs": SiNodedotjs,
  "docker": SiDocker,
  "dockerfile": SiDocker,
  "image": SiDocker,
  "oci": SiDocker,
  "sqlserver": SiMysql,
  "mssql": SiMysql,
  "oracle": SiMysql,
  "mongo": SiMongodb,
  "elastic": SiElasticsearch,
  "jenkins": SiJenkins,
  "jupyterlab": SiJupyter,
  "nginx-proxy": SiNginx,
  "nginx-static": SiNginx,
  "wg-easy": SiWireguard,
  "searxng": SiSearxng,
  "home-assistant": SiHomeassistant,
  "portainer": SiPortainer,
  "rocket-chat": SiRocketdotchat,
  "odoo": SiOdoo,
  "tailscale": SiTailscale,
  "cloudflared": SiCloudflare,
  "postgres-admin": SiPostgresql,
  "matrix": SiMatrix,
  "element": SiElement,
  "calcom": SiCaldotcom,
  "firefly": SiFireflyiii,
  "actual": SiActualbudget,
  "hedgedoc": SiHedgedoc,
  "joplin": SiJoplin,
  "drone": SiDrone,
  "octoprint": SiOctoprint,
};

export function TechIcon({ name, size = 20, className = "" }: { name?: string; size?: number; className?: string }) {
  const key = (name ?? "").toLowerCase();
  const Icon = MAP[key];
  if (Icon) {
    return <Icon size={size} className={className} aria-hidden="true" />;
  }
  return (
    <span
      aria-hidden="true"
      style={{ width: size, height: size, fontSize: size * 0.62, lineHeight: `${size}px` }}
      className={`inline-flex items-center justify-center rounded-full bg-primary/15 text-primary font-semibold select-none ${className}`}
    >
      <span className="material-symbols-outlined" style={{ fontSize: size * 0.75 }}>
        {CATEGORY_FALLBACK[key] ?? "apps"}
      </span>
    </span>
  );
}

const CATEGORY_FALLBACK: Record<string, string> = {
  database: "database",
  cache: "memory",
  web: "language",
  runtime: "code",
  monitoring: "monitoring",
  cms: "article",
  ai: "smart_toy",
  collaboration: "forum",
  security: "lock",
  storage: "storage",
  media: "movie",
  iot: "home",
  analytics: "monitoring",
  developer: "code",
  tools: "apps",
  messaging: "hub",
  questdb: "database",
  typesense: "search",
  weaviate: "search",
  chroma: "palette",
  redpanda: "hub",
  emqx: "hub",
  haproxy: "language",
  openresty: "language",
  varnish: "language",
  tinyproxy: "language",
  frp: "language",
  alertmanager: "notifications_active",
  zabbix: "monitoring",
  pyroscope: "monitoring",
  glances: "monitoring",
  wikijs: "article",
  docmost: "article",
  flowise: "smart_toy",
  comfyui: "smart_toy",
  khoj: "smart_toy",
  theia: "code",
  casdoor: "lock",
  crowdsec: "security",
  wazuh: "security",
  blocky: "dns",
  restic: "backup",
  samba: "folder",
  filebrowser: "folder",
  prowlarr: "search",
  photoprism: "photo",
  navidrome: "music_note",
  kestra: "monitoring",
  pgadmin: "database",
  nocodb: "grid_view",
  tooljet: "code",
  dashy: "apps",
  heimdall: "apps",
  linkding: "bookmark",
  miniflux: "rss_feed",
  planka: "view_kanban",
  kanboard: "view_kanban",
  cyberchef: "security",
  gotify: "notifications",
  shlink: "link",
  kutt: "link",
  terminal: "terminal",
  trilium: "book",
  siyuan: "description",
  silverbullet: "bolt",
  stirling: "picture_as_pdf",
  anythingllm: "smart_toy",
  textgen: "smart_toy",
  woodpecker: "code_blocks",
  focalboard: "view_kanban",
  pingvin: "share",
  snapdrop: "swap_calls",
  metube: "download",
  tubesync: "subscriptions",
  jellyseerr: "movie",
  komga: "auto_stories",
  shiori: "bookmarks",
  whoogle: "travel_explore",
  mailpit: "email",
  smtp4dev: "email",
  rustdesk: "monitor",
  archivebox: "archive",
  monica: "volunteer_activism",
  dokuwiki: "menu_book",
  homebox: "inventory_2",
};
